name: Deploy to Staging

on:
  push:
    branches:
      - staging
env:
  REGION: us-central1
  PROJECT_ID: spry-metric-460820-i8
  SERVICE_NAME: ecr-financy-front

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Autenticação via Service Account Key (Adicione o JSON da chave nos Secrets do GitHub como GCP_SA_KEY)
      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      - name: Build and Push Container
        run: |
          docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }} .
          docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          flags: '--allow-unauthenticated --port 3000 --service-account cloud-run-sa@spry-metric-460820-i8.iam.gserviceaccount.com'

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
